name: Base

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    main_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Echo pr message
              run: echo "${{ toJSON(github.event.pull_request) }}"
            - uses: actions/github-script@v6
              id: create-body
              with:
                  result-encoding: string
                  script: |
                      const commitMessage = ${{ toJSON(github.event.pull_request.body) }}
                      const resultMessage = `":github: ビルド結果: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n メッセージ: ${commitMessage}"`
                      const body = {
                        "text": ":github: ${{ job.status }}\n\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
                        "blocks": [
                            {
                                "type": "section",
                                "text": {
                                        "type": "mrkdwn",
                                        "text": resultMessage,
                                }
                            },
                            {
                                "type": "context",
                                "elements": [
                                    {
                                        "type": "mrkdwn",
                                        "text": "Author: <https://github.com/${{ github.event.sender.login }}|@${{ github.event.sender.login }}>"
                                    }
                                ]
                            }
                        ]
                      }
                      return JSON.stringify(body)
            - name: Send GitHub Action trigger data to Slack workflow
              id: slack
              uses: slackapi/slack-github-action@v1.24.0
              env:
                  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
              with:
                  payload: ${{ steps.create-body.outputs.result }}
